Repository lenard123/techgear, pull requests merged in 2021-10, with the labels that each got.

#153 Fix tailwind link
  api/templates/404_template.php
Labels: hacktoberfest-accepted

#157 Create Add Product Feature
  api/Controllers/Admin/ProductController.php
  api/templates/admin/product_add_page.php
Labels: enhancement

#160 [Enhance] Product default Image
  api/Models/Product.php
  public/assets/img/product-default.jpg
Labels: enhancement

#162 Ftr add product image upload
  api/Controllers/Admin/ProductController.php
  api/Models/Product.php
  api/Utils/Storage.php
  api/config/config.php
  api/config/storage.php
  api/templates/admin/product_add_page.php
Labels: feature

#164 Ftr cloudinary upload
  api/Models/Product.php
  api/Utils/Storage.php
  api/config/storage.php
  composer.json
  composer.lock
Labels: feature

#166 Enh 4/3 image ratio
  api/templates/admin/product_add_page.php
  api/templates/admin/product_page.php
  api/templates/components/admin_layout.php
  api/templates/components/cart_card.php
  api/templates/components/customer_layout.php
  api/templates/components/product_card.php
  api/templates/customer/favorites_page.php
  api/templates/customer/product_page.php
  public/assets/css/admin.css
  public/assets/css/all.css
  public/assets/css/styles.css
Labels: enhancement

#169 Fix base url
  .env.example
  api/config/app.php
  api/helpers/url.php
Labels: enhancement

#170 Separate Customer Sidebar Component
  api/Components/CustomerLayoutComponent.php
  api/Components/CustomerSidebarComponent.php
  api/templates/components/customer_header.php
  api/templates/components/customer_layout.php
  api/templates/components/customer_sidebar.php
Labels: enhancement

#172 Product Image Can now be preview before uploading
  api/templates/admin/product_add_page.php
  front-end/es6/admin-product-add.js
  public/assets/js/admin-product-add.js
Labels: enhancement

#174 [Feature] Crop Image before uploading
  .gitignore
  api/Components/LayoutComponent.php
  api/Controllers/Admin/ProductController.php
  api/templates/admin/product_add_page.php
  api/templates/components/admin_layout.php
  front-end/es6/admin-product-add.js
  public/assets/css/all.css
  public/assets/js/admin-product-add.js
  public/assets/lib/cropper.js
Labels: feature

#177 Bugfix limit purchases input
  api/Controllers/Admin/ProductController.php
  api/templates/admin/product_add_page.php
Labels: bug-fix

#180 [Enhancement] Enable tailwind jitmode
  front-end/css/tailwind.css
  package.json
  tailwind.config.js
Labels: enhancement

#190 Ftr design for admin sign in
  api/templates/admin/signin_page.php
Labels: feature, front-end

#194 [Feature] tooltip component
  api/Components/CustomerLayoutComponent.php
  api/Components/LayoutComponent.php
  api/Controllers/Customer/CartController.php
  front-end/es6/app.js
  public/assets/js/app.js
Labels: enhancement, feature, front-end
